# Generated by Django 4.0.4 on 2022-05-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table_inventory',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_number', models.IntegerField()),
                ('left_side', models.IntegerField()),
                ('right_side', models.IntegerField()),
            ],
            options={
                'db_table': 'table_inventory',
            },
        ),
    ]
