# Generated by Django 4.0.4 on 2022-05-19 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
